### ISSUE TITLE
PreventRemoteMovement

### ISSUE THREAD

**Issue by Darkhax** [MinecraftModDevelopment/Modding-Resources#4]
Hi, could someone consider adding this to our resources? 

https://www.reddit.com/r/feedthebeast/comments/7sytf5/found_out_why_my_world_was_lagging/dt9a76b/?context=3&st=jcvlyn82&sh=1e4018d8

**Comment by antoinegag** [comment]
Will do this ~~week-end~~ next update, thanks.
