### ISSUE TITLE
Another great mapping viewer

### ISSUE THREAD

**Issue by ElBread3** [MinecraftModDevelopment/Modding-Resources#42]
Here's another mapping viewer for basically all types of mapping types. The big difference with this one is that it shows the obfuscated names, which is good for writing ASM. Author is named William Gray:
https://wagyourtail.xyz/Projects/MinecraftMappingViewer/App

**Comment by ElBread3** [comment]
There's also https://linkie.shedaniel.me/mappings
For 1.14+ if I recall

**Comment by KiriCattus** [comment]
Sorted one but the other was broken when tested by two people on our end so that one can be tried later
